/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;
import exceptions.CantCheckId;
import exceptions.NotName;
import ficheros.ClassFichero;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.validations.UserDataValidations;

/**
 *
 * @author carlessalfor
 */
public class JFrame_Main extends javax.swing.JFrame {
    int errores = 0;
    /**
     * Creates new form JFrame_Main
     */
    
    public JFrame_Main() throws FileNotFoundException {
        ClassFichero.createFile("user_data_cs.csv");
        initComponents();
        initConfig();
        ClassFichero.writeFile("nombre;nif;fecha_nac; edad;cod:post\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Logo = new javax.swing.JLabel();
        jLabel_nombreU = new javax.swing.JLabel();
        jTextField_NIF = new javax.swing.JTextField();
        jLabel_nifERROR = new javax.swing.JLabel();
        jButton_Validar = new javax.swing.JButton();
        jLabel_nameERROR = new javax.swing.JLabel();
        jLabel_nombreU1 = new javax.swing.JLabel();
        jTextField_Nombre1 = new javax.swing.JTextField();
        jLabel_nombreU2 = new javax.swing.JLabel();
        jTextField_Fecha = new javax.swing.JTextField();
        jLabel_fechaERROR = new javax.swing.JLabel();
        jLabel_codpERROR = new javax.swing.JLabel();
        jLabel_nombreU3 = new javax.swing.JLabel();
        jTextField_CodP = new javax.swing.JTextField();
        jLabel_emailERROR = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel_nombreU4 = new javax.swing.JLabel();
        jButton_Clear = new javax.swing.JButton();
        jButton_CSV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMostrarEdad = new javax.swing.JTextField();
        jemojiLike = new javax.swing.JLabel();
        lemojiDislike = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_Titulo.setText("Carles Salvany Validaciones");

        jLabel_Logo.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/media/monki-flip-monkey.gif"))); // NOI18N
        jLabel_Logo.setText("jLabel2");

        jLabel_nombreU.setText("NIF");

        jLabel_nifERROR.setForeground(new java.awt.Color(204, 0, 0));

        jButton_Validar.setText("Validar");
        jButton_Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ValidarActionPerformed(evt);
            }
        });

        jLabel_nameERROR.setForeground(new java.awt.Color(204, 0, 0));

        jLabel_nombreU1.setText("Nombre");

        jTextField_Nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Nombre1ActionPerformed(evt);
            }
        });

        jLabel_nombreU2.setText("FECHA");

        jTextField_Fecha.setToolTipText("");

        jLabel_fechaERROR.setForeground(new java.awt.Color(204, 0, 0));

        jLabel_codpERROR.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_codpERROR.setLabelFor(jButton_CSV);

        jLabel_nombreU3.setText("CODIGO POSTAL");

        jLabel_emailERROR.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_emailERROR.setText("hghf");

        jLabel_nombreU4.setText("Email");

        jButton_Clear.setText("Clear");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jButton_CSV.setText("CSV");
        jButton_CSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CSVActionPerformed(evt);
            }
        });

        jLabel1.setText("Edad:");

        jMostrarEdad.setEditable(false);
        jMostrarEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMostrarEdadActionPerformed(evt);
            }
        });

        jemojiLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/media/likeemoji.jpg"))); // NOI18N
        jemojiLike.setToolTipText("");

        lemojiDislike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/media/dislikeemoji.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lemojiDislike)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel_nombreU3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_CodP, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel_codpERROR))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel_nombreU2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel_fechaERROR))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel_nombreU4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel_emailERROR))
                                .addComponent(jLabel_Titulo)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel_nombreU)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_NIF, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel_nifERROR))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel_nombreU1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel_nameERROR))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jMostrarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_Validar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Clear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_CSV)))
                            .addGap(96, 96, 96)
                            .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jemojiLike, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jMostrarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_nombreU)
                            .addComponent(jTextField_NIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nifERROR))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_nombreU1)
                            .addComponent(jTextField_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nameERROR))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_nombreU2)
                            .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_fechaERROR))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_nombreU3)
                            .addComponent(jTextField_CodP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_codpERROR)))
                    .addComponent(jLabel_Logo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_nombreU4)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_emailERROR))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Validar)
                            .addComponent(jButton_Clear)
                            .addComponent(jButton_CSV))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lemojiDislike)
                            .addComponent(jemojiLike))
                        .addGap(73, 73, 73))))
        );

        jTextField_Fecha.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initConfig(){
        jemojiLike.setVisible(false);
        lemojiDislike.setVisible(false);
    }
    
    private void guardarDatos(){
        String nif = jTextField_NIF.getText();
        String nombre = jTextField_Nombre1.getText();
        String fecha = jTextField_Fecha.getText();
        String codigoP = jTextField_CodP.getText();
        String edad = jMostrarEdad.getText();
        
        ClassFichero.writeFile(nombre + ";" + nif + ";" + fecha + ";" + edad + ";" + codigoP + "\n");
    }
    private void jButton_ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ValidarActionPerformed
        // TODO add your handling code here:
        errores = 0;
        jemojiLike.setVisible(false);
        lemojiDislike.setVisible(false);
        String nif = jTextField_NIF.getText();
        String nombre = jTextField_Nombre1.getText();
        String fecha = jTextField_Fecha.getText();
        String codigoP = jTextField_CodP.getText();
        try{
            UserDataValidations.checkId(1, nif);
            jLabel_nifERROR.setText("");
        }catch(CantCheckId err){
            jLabel_nifERROR.setText(err.getMessage());
            errores ++;
        }
       try{
            UserDataValidations.checkName(nombre);
            jLabel_nameERROR.setText("");
        }catch(NotName err){
            jLabel_nameERROR.setText(err.getMessage());
            errores ++;
        }
       
        if (!UserDataValidations.checkFecha(fecha)){
            jLabel_fechaERROR.setText("Fecha incorrecto");
            errores ++;
        }
        else{
            jLabel_fechaERROR.setText("");
            int edad = UserDataValidations.calculadoraFecha(fecha);
            jMostrarEdad.setText(Integer.toString(edad));
        }
        if (!UserDataValidations.checkPostalCode(codigoP)){
            jLabel_codpERROR.setText("Codigo postal incorrecto");
            errores ++;
        }
        else{jLabel_codpERROR.setText("");}
        
        if (errores == 0){
        jemojiLike.setVisible(true);
        }
        else{
            lemojiDislike.setVisible(true);
        }
    }//GEN-LAST:event_jButton_ValidarActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        jLabel_nifERROR.setText("");
        jLabel_nameERROR.setText("");
        jLabel_fechaERROR.setText("");
        jLabel_codpERROR.setText("");
        jTextField_CodP.setText("");
        jTextField_Fecha.setText("");
        jTextField_Nombre1.setText("");
        jTextField_NIF.setText("");
        jMostrarEdad.setText("");
        errores = 0;
        jemojiLike.setVisible(false);
        lemojiDislike.setVisible(false);
        
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_CSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CSVActionPerformed
        // TODO add your handling code here:
        guardarDatos();
    }//GEN-LAST:event_jButton_CSVActionPerformed

    private void jTextField_Nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nombre1ActionPerformed

    private void jMostrarEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMostrarEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMostrarEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrame_Main().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(JFrame_Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CSV;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Validar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_codpERROR;
    private javax.swing.JLabel jLabel_emailERROR;
    private javax.swing.JLabel jLabel_fechaERROR;
    private javax.swing.JLabel jLabel_nameERROR;
    private javax.swing.JLabel jLabel_nifERROR;
    private javax.swing.JLabel jLabel_nombreU;
    private javax.swing.JLabel jLabel_nombreU1;
    private javax.swing.JLabel jLabel_nombreU2;
    private javax.swing.JLabel jLabel_nombreU3;
    private javax.swing.JLabel jLabel_nombreU4;
    private javax.swing.JTextField jMostrarEdad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_CodP;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Fecha;
    private javax.swing.JTextField jTextField_NIF;
    private javax.swing.JTextField jTextField_Nombre1;
    private javax.swing.JLabel jemojiLike;
    private javax.swing.JLabel lemojiDislike;
    // End of variables declaration//GEN-END:variables
}
